import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import path from 'path';
import { access, copyFile, mkdir, readFile, writeFile } from 'fs/promises';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === 'production';
const DEFAULT_OBSIDIAN_VAULT = '/Users/dev/Documents/Vaults/Test';
const OBSIDIAN_PLUGIN_ID = 'knowlery';
const OBSIDIAN_PLUGIN_ASSETS = ['main.js', 'manifest.json', 'styles.css'];
const targetVault = process.env.OBSIDIAN_VAULT || DEFAULT_OBSIDIAN_VAULT;
const targetPluginDir = path.join(targetVault, '.obsidian', 'plugins', OBSIDIAN_PLUGIN_ID);

async function copyToVault() {
  try {
    await access(targetVault);
  } catch {
    console.log(`Skipping vault copy because ${targetVault} is not available`);
    return;
  }

  await mkdir(targetPluginDir, { recursive: true });
  await Promise.all(
    OBSIDIAN_PLUGIN_ASSETS.map((asset) => copyFile(asset, path.join(targetPluginDir, asset))),
  );
  console.log(`Copied ${OBSIDIAN_PLUGIN_ASSETS.join(', ')} to ${targetPluginDir}`);
}

const QUERY_SCRIPT_MODULE = 'src/assets/query-script.generated.ts';

// Replaces dependency internals that trip the community plugin scanner with inert
// shims: legacy-browser polyfills in jszip's dependency chain create <script> elements,
// and js-yaml / gray-matter carry `new Function` / `eval` code paths Knowlery never
// uses (safe YAML schema only, no JS frontmatter). See build/shims/*.js.
const scannerHygieneShims = {
  name: 'scanner-hygiene-shims',
  setup(build) {
    const shim = (file) => ({ path: path.resolve('build/shims', file) });
    // Resolve jszip to its source entry instead of the pre-bundled dist/jszip.min.js
    // (the package's `browser` field remaps to the dist build, which has the legacy
    // polyfills already inlined and out of reach of the aliases below).
    build.onResolve({ filter: /^jszip$/ }, () => ({
      path: path.resolve('node_modules/jszip/lib/index.js'),
    }));
    build.onResolve({ filter: /^immediate$/ }, () => shim('immediate.js'));
    build.onResolve({ filter: /^setimmediate$/ }, () => shim('setimmediate.js'));
    build.onResolve({ filter: /\/function$/ }, (args) => {
      if (args.importer.split(path.sep).join('/').includes('js-yaml/lib/js-yaml')) {
        return shim('js-yaml-function-type.js');
      }
      return undefined;
    });
    // gray-matter reaches its engines as both './engines' and './lib/engines'.
    build.onResolve({ filter: /\/engines$/ }, (args) => {
      if (args.importer.split(path.sep).join('/').includes('gray-matter')) {
        return shim('gray-matter-engines.js');
      }
      return undefined;
    });
  },
};

// Pre-pass: bundle the vault-side retrieval script (spec f2, §5.3) and embed it as a
// string constant so the plugin can write it into vaults. Output is deliberately
// independent of the prod flag (never minified) so the committed generated file is
// deterministic and CI can diff it as a drift guard.
async function buildQueryScript() {
  const result = await esbuild.build({
    entryPoints: ['src/query-cli/main.ts'],
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node18',
    minify: false,
    write: false,
    logLevel: 'silent',
    // gray-matter is CJS and requires node builtins at runtime; ESM output needs a
    // require shim for those calls to resolve under plain `node`.
    banner: {
      js: "import { createRequire as __createRequire } from 'node:module';\nconst require = __createRequire(import.meta.url);",
    },
    plugins: [scannerHygieneShims],
  });
  const code = result.outputFiles[0].text;
  const moduleText = [
    '// AUTO-GENERATED by esbuild.config.mjs from src/query-cli/ — do not edit by hand.',
    '// Regenerate with `npm run build` (or any esbuild invocation). CI diffs this file.',
    '/* eslint-disable */',
    `export const QUERY_SCRIPT: string = ${JSON.stringify(code)};`,
    '',
  ].join('\n');
  const existing = await readFile(QUERY_SCRIPT_MODULE, 'utf8').catch(() => null);
  if (existing !== moduleText) {
    await writeFile(QUERY_SCRIPT_MODULE, moduleText);
    console.log(`Regenerated ${QUERY_SCRIPT_MODULE}`);
  }
}

await buildQueryScript();

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
    ...builtins.map((name) => `node:${name}`),
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  minify: prod,
  outfile: 'main.js',
  plugins: [scannerHygieneShims, {
    name: 'copy-to-obsidian-vault',
    setup(build) {
      build.onEnd(async (result) => {
        if (result.errors.length > 0) return;
        await copyToVault();
      });
    },
  }],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
