import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import path from 'path';
import { access, copyFile, mkdir } from 'fs/promises';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === 'production';
const DEFAULT_OBSIDIAN_VAULT = '/Users/dev/Documents/Vaults/Test';
const OBSIDIAN_PLUGIN_ID = 'knowlery';
const OBSIDIAN_PLUGIN_ASSETS = ['main.js', 'manifest.json', 'styles.css'];
const targetVault = process.env.OBSIDIAN_VAULT || DEFAULT_OBSIDIAN_VAULT;
const targetPluginDir = path.join(targetVault, '.obsidian', 'plugins', OBSIDIAN_PLUGIN_ID);

async function copyToVault() {
  try {
    await access(targetVault);
  } catch {
    console.log(`Skipping vault copy because ${targetVault} is not available`);
    return;
  }

  await mkdir(targetPluginDir, { recursive: true });
  await Promise.all(
    OBSIDIAN_PLUGIN_ASSETS.map((asset) => copyFile(asset, path.join(targetPluginDir, asset))),
  );
  console.log(`Copied ${OBSIDIAN_PLUGIN_ASSETS.join(', ')} to ${targetPluginDir}`);
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  minify: prod,
  outfile: 'main.js',
  plugins: [{
    name: 'copy-to-obsidian-vault',
    setup(build) {
      build.onEnd(async (result) => {
        if (result.errors.length > 0) return;
        await copyToVault();
      });
    },
  }],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
