import matter from 'gray-matter';
import type { BundleManifest } from '../../types';
import type { RawDependency } from './shared';
import { safeMatter, titleFromPath } from './shared';

export function buildReadme(manifest: BundleManifest): string {
  return matter.stringify([
    `# ${manifest.title}`,
    '',
    `This is a portable knowledge bundle. Point your agent at \`${manifest.entrypoint}\` and it can navigate the included knowledge pages, sources, and update log.`,
    '',
    `- Concepts: ${manifest.conceptCount}`,
    `- Creator: ${manifest.creator.name || 'Unknown'}`,
    `- Released: ${manifest.releasedAt}`,
    '',
    'Generated by Knowlery.',
    '',
  ].join('\n'), {
    type: 'Reference',
    title: `${manifest.title} README`,
  });
}

export function buildSourceCopy(raw: RawDependency): string {
  const parsed = safeMatter(raw.body);
  const data: Record<string, unknown> = { ...raw.frontmatter, ...parsed.data };
  const existingType = data.type;
  if (typeof existingType === 'string' && existingType.trim()) {
    data.knowlery_raw_type = existingType;
  }
  data.type = 'Source';
  data.title = stringOr(data.title, raw.title || titleFromPath(raw.path));
  data.knowlery_raw_path = raw.path;
  return matter.stringify(parsed.content.trimStart(), data);
}

function stringOr(value: unknown, fallback: string): string {
  return typeof value === 'string' && value.trim() ? value : fallback;
}
