import type { VaultFs } from './vault-fs';
import { normalizeVaultPath } from './vault-fs';
import { collectRuleImportPaths } from './rule-imports';

export const AGENTS_MD_PATH = 'AGENTS.md';
export const AGENTS_MD_MANAGED_START = '<!-- Knowlery managed:start -->';
export const AGENTS_MD_MANAGED_END = '<!-- Knowlery managed:end -->';

export interface AgentsMdRule {
  /** Path relative to the rules directory, e.g. `citation-required.md`. */
  path: string;
  content: string;
}

export interface AgentsMdSource {
  knowledgeMd: string;
  rulesDir: string;
  rules: AgentsMdRule[];
}

/**
 * Codex and OpenCode read a vault-root `AGENTS.md` and neither supports Claude
 * Code's `@path` imports, so the fixed context `.claude/CLAUDE.md` assembles by
 * reference (`@../KNOWLEDGE.md` + `@rules/*.md`) has to be inlined here to give
 * every platform the same operating card and rules. The block is regenerated
 * from the source files on sync; user prose outside the markers is preserved.
 *
 * Size note: Codex caps the whole project-instruction chain at 32 KiB by default
 * (`project_doc_max_bytes`). The default card plus the four bundled rules is
 * roughly 10 KB, leaving headroom for user rules.
 */
export function renderAgentsMdBlock(source: AgentsMdSource): string {
  const sections = [
    source.knowledgeMd.trim(),
    ...source.rules.map((rule) => rule.content.trim()),
  ].filter((section) => section.length > 0);

  return [
    AGENTS_MD_MANAGED_START,
    `<!-- Generated by Knowlery from KNOWLEDGE.md and ${source.rulesDir}/*.md — the same fixed context Claude Code loads through .claude/CLAUDE.md. Edit those source files, not this block; it is rewritten on sync. Text outside the markers is yours and is kept. -->`,
    '',
    sections.join('\n\n'),
    '',
    AGENTS_MD_MANAGED_END,
  ].join('\n');
}

export function mergeAgentsMd(existing: string | null, block: string): string {
  if (existing === null || existing.trim().length === 0) {
    return `${block}\n`;
  }

  const start = existing.indexOf(AGENTS_MD_MANAGED_START);
  const end = existing.indexOf(AGENTS_MD_MANAGED_END, start + AGENTS_MD_MANAGED_START.length);
  if (start !== -1 && end !== -1) {
    const before = existing.slice(0, start);
    const after = existing.slice(end + AGENTS_MD_MANAGED_END.length);
    return `${before}${block}${after.endsWith('\n') ? after : `${after}\n`}`;
  }

  return `${existing.trimEnd()}\n\n${block}\n`;
}

export async function readAgentsMdSource(fs: VaultFs, rulesDir: string): Promise<AgentsMdSource | null> {
  if (!(await fs.exists('KNOWLEDGE.md'))) return null;
  const knowledgeMd = await fs.read('KNOWLEDGE.md');

  const normalizedRulesDir = normalizeVaultPath(rulesDir);
  const rulePaths = await collectRuleImportPaths(fs, normalizedRulesDir);
  const rules: AgentsMdRule[] = [];
  for (const path of rulePaths) {
    rules.push({ path, content: await fs.read(`${normalizedRulesDir}/${path}`) });
  }

  return { knowledgeMd, rulesDir: normalizedRulesDir, rules };
}

/**
 * Write-on-change, like `syncClaudeRuleImports`: an unconditional write would churn
 * the file's mtime on every plugin load. Skips silently when KNOWLEDGE.md is absent
 * (the vault is not initialized).
 */
export async function syncAgentsMd(fs: VaultFs, rulesDir: string): Promise<void> {
  const source = await readAgentsMdSource(fs, rulesDir);
  if (!source) return;

  const fileExists = await fs.exists(AGENTS_MD_PATH);
  const existing = fileExists ? await fs.read(AGENTS_MD_PATH) : null;
  const merged = mergeAgentsMd(existing, renderAgentsMdBlock(source));
  if (!fileExists || merged !== existing) {
    await fs.write(AGENTS_MD_PATH, merged);
  }
}
