import matter from 'gray-matter';
import type { VaultFs } from './vault-fs';
import { normalizeVaultPath } from './vault-fs';
import { generateOperatingRules } from '../assets/templates';
import { MANAGED_BLOCK_END, MANAGED_BLOCK_START, mergeManagedBlock, wrapManagedBlock } from './managed-block';

export const AGENTS_MD_PATH = 'AGENTS.md';
/**
 * The one rules directory, for every platform. `.agents/` is the vendor-neutral
 * home the skills already use (`.agents/skills/` is the Codex convention and
 * Knowlery's canonical skills dir); there is no cross-vendor "rules" standard,
 * so the rules are delivered by inlining them into AGENTS.md and by `@`-importing
 * them from `.claude/CLAUDE.md`, not by a per-platform directory.
 */
export const RULES_DIR = '.agents/rules';
export const AGENTS_MD_MANAGED_START = MANAGED_BLOCK_START;
export const AGENTS_MD_MANAGED_END = MANAGED_BLOCK_END;

export interface AgentsMdRule {
  /** Path relative to the rules directory, e.g. `citation-required.md`. */
  path: string;
  content: string;
}

export interface AgentsMdSource {
  knowledgeMd: string;
  /** Sorted by path. */
  rules: AgentsMdRule[];
}

/**
 * AGENTS.md (agents.md, Agentic AI Foundation) is the entry file for Codex and
 * OpenCode (Cursor, Gemini CLI and others read it too). Neither supports an
 * import syntax — Codex concatenates the AGENTS.md chain only, OpenCode V2 does
 * not resolve `@` references or its `instructions` array — and a "read these
 * files first" instruction did not survive acceptance: OpenCode went straight to
 * a skill and never read KNOWLEDGE.md or the rules. So for these harnesses the
 * sources are *copied* into the block: the user's KNOWLEDGE.md first (the most
 * important part of the prompt), Knowlery's operating rules for the running
 * version (rendered from the template, so wording fixes reach every vault), then
 * every rule in `.agents/rules/`. KNOWLEDGE.md and the rule files remain the
 * sources of truth — the block is regenerated from them on every sync. Claude
 * Code does not read this file; its entry is `.claude/CLAUDE.md`
 * (core/claude-md.ts), which `@`-imports the same sources instead of copying.
 *
 * Size note: Codex caps the whole project-instruction chain at 32 KiB by default
 * (`project_doc_max_bytes`). A cleaned-up KNOWLEDGE.md plus the operating rules
 * and the four bundled rules is roughly 10 KB.
 */
export function renderAgentsMdBlock(source: AgentsMdSource): string {
  return wrapManagedBlock(
    `Generated by Knowlery from KNOWLEDGE.md (your description of this knowledge base), Knowlery's operating rules for this version, and ${RULES_DIR}/*.md. Codex and OpenCode read this file and cannot import, so those sources are copied in here; Claude Code uses .claude/CLAUDE.md, which imports them. Edit KNOWLEDGE.md or the rule files, not this block; it is rewritten on sync. Text outside the markers is yours and is kept.`,
    [
      source.knowledgeMd.trim(),
      generateOperatingRules().trim(),
      ...source.rules.map((rule) => renderRuleBody(rule.content)),
    ],
  );
}

/**
 * Claude Code scopes a rule to files via `paths:` frontmatter. Other platforms
 * have no such mechanism, so inlining the YAML verbatim would leave a bare `---`
 * block mid-document; the scope is restated as a sentence under the heading instead.
 */
export function renderRuleBody(content: string): string {
  let parsed: ReturnType<typeof matter>;
  try {
    parsed = matter(content);
  } catch {
    return content.trim();
  }

  const body = parsed.content.trim();
  const paths = Array.isArray(parsed.data.paths)
    ? (parsed.data.paths as unknown[]).filter((path): path is string => typeof path === 'string')
    : typeof parsed.data.paths === 'string'
      ? parsed.data.paths.split(',').map((path) => path.trim()).filter((path) => path.length > 0)
      : [];
  if (paths.length === 0) return body;

  const scope = `_Applies to files matching: ${paths.map((path) => `\`${path}\``).join(', ')}_`;
  const [firstLine, ...rest] = body.split('\n');
  return firstLine.startsWith('#')
    ? [firstLine, '', scope, ...rest].join('\n')
    : [scope, '', body].join('\n');
}

/** Every `.md` under `dir`, recursively, as sorted paths relative to `dir`. */
export async function collectRulePaths(fs: VaultFs, dir: string = RULES_DIR): Promise<string[]> {
  const root = normalizeVaultPath(dir);
  if (!(await fs.exists(root))) return [];

  const found: string[] = [];
  async function walk(current: string): Promise<void> {
    const listing = await fs.list(normalizeVaultPath(current));
    for (const filePath of listing.files) {
      const normalized = normalizeVaultPath(filePath);
      if (!normalized.endsWith('.md')) continue;
      if (!normalized.startsWith(`${root}/`)) continue;
      found.push(normalized.slice(root.length + 1));
    }
    for (const folderPath of listing.folders) {
      await walk(folderPath);
    }
  }
  await walk(root);

  return [...new Set(found)].sort((a, b) => a.localeCompare(b));
}

/** Null when the vault is not initialized (no KNOWLEDGE.md). */
export async function readAgentsMdSource(fs: VaultFs): Promise<AgentsMdSource | null> {
  if (!(await fs.exists('KNOWLEDGE.md'))) return null;
  const knowledgeMd = await fs.read('KNOWLEDGE.md');

  const rules: AgentsMdRule[] = [];
  for (const path of await collectRulePaths(fs)) {
    rules.push({ path, content: await fs.read(`${RULES_DIR}/${path}`) });
  }

  return { knowledgeMd, rules };
}

/**
 * Write-on-change: an unconditional write would churn the file's mtime on every
 * plugin load. Skips silently when KNOWLEDGE.md is absent (vault not initialized).
 */
export async function syncAgentsMd(fs: VaultFs): Promise<void> {
  const source = await readAgentsMdSource(fs);
  if (!source) return;

  const fileExists = await fs.exists(AGENTS_MD_PATH);
  const existing = fileExists ? await fs.read(AGENTS_MD_PATH) : null;
  const merged = mergeManagedBlock(existing, renderAgentsMdBlock(source));
  if (!fileExists || merged !== existing) {
    await fs.write(AGENTS_MD_PATH, merged);
  }
}

/**
 * The explicit, user-initiated cleanup: rewrites AGENTS.md as the managed block
 * alone, discarding everything outside the markers (typically the pre-Knowlery
 * instructions a vault carried). Sync never does this on its own.
 */
export async function resetAgentsMd(fs: VaultFs): Promise<void> {
  const source = await readAgentsMdSource(fs);
  if (!source) return;
  await fs.write(AGENTS_MD_PATH, mergeManagedBlock(null, renderAgentsMdBlock(source)));
}
