import type { VaultFs } from './vault-fs';
import { normalizeVaultPath } from './vault-fs';
import { generateOperatingRules } from '../assets/templates';
import { MANAGED_BLOCK_END, MANAGED_BLOCK_START, mergeManagedBlock, wrapManagedBlock } from './managed-block';

export const AGENTS_MD_PATH = 'AGENTS.md';
/**
 * The one rules directory, for every platform. `.agents/` is the vendor-neutral
 * home the skills already use (`.agents/skills/` is the Codex convention and
 * Knowlery's canonical skills dir); there is no cross-vendor "rules" standard,
 * so each entry file points at the rule files here instead of a per-platform
 * directory (AGENTS.md by path, `.claude/CLAUDE.md` by `@` import).
 */
export const RULES_DIR = '.agents/rules';
export const AGENTS_MD_MANAGED_START = MANAGED_BLOCK_START;
export const AGENTS_MD_MANAGED_END = MANAGED_BLOCK_END;

export interface AgentsMdSource {
  /** Paths relative to the rules directory, sorted, e.g. `citation-required.md`. */
  rulePaths: string[];
}

/**
 * AGENTS.md (agents.md, Agentic AI Foundation) is the entry file for Codex and
 * OpenCode (Cursor, Gemini CLI and others read it too). Neither supports an
 * import syntax — Codex concatenates the AGENTS.md chain only, OpenCode V2 does
 * not resolve `@` references or its `instructions` array — so KNOWLEDGE.md and
 * the rules are *referenced*, not inlined: the block opens by telling the agent
 * to read KNOWLEDGE.md first and then each rule file, and carries only Knowlery's
 * operating rules for the running version (rendered from the template, so wording
 * fixes reach every vault). KNOWLEDGE.md stays a standalone file that is never
 * copied anywhere. Claude Code does not read this file; its entry is
 * `.claude/CLAUDE.md` (core/claude-md.ts), where the same references are hard
 * `@` imports.
 *
 * The block is regenerated on sync; user prose outside the markers is preserved.
 */
export function renderAgentsMdBlock(source: AgentsMdSource): string {
  return wrapManagedBlock(
    `Generated by Knowlery: its operating rules for this version, plus pointers to KNOWLEDGE.md (your description of this knowledge base) and ${RULES_DIR}/*.md. Codex and OpenCode read this file; Claude Code uses .claude/CLAUDE.md instead. Edit KNOWLEDGE.md or the rule files, not this block; it is rewritten on sync. Text outside the markers is yours and is kept.`,
    [renderReadFirst(source.rulePaths), generateOperatingRules().trim()],
  );
}

/**
 * The soft reference. Codex and OpenCode cannot be made to inject these files,
 * so the instruction has to carry its own weight: say what KNOWLEDGE.md is, that
 * it is not injected, and exactly how to read it (a vault note → Obsidian CLI
 * when running) and the rules (dot-directory → file tools, per the operating
 * card's boundary).
 */
export function renderReadFirst(rulePaths: string[]): string {
  const hasRules = rulePaths.length > 0;
  const lines = [
    '## Read First',
    '',
    `Do ${hasRules ? 'these two steps' : 'this'} before your first reply in this session — before answering, planning,`,
    `or invoking any skill. ${hasRules ? 'These files are' : 'This file is'} **not** injected automatically, and no skill`,
    `substitutes for reading ${hasRules ? 'them' : 'it'}.`,
    '',
    '1. Read `KNOWLEDGE.md` at the vault root in full: `obsidian read file="KNOWLEDGE.md"` when',
    '   Obsidian is running, otherwise your file tools. It is the user\'s description of this',
    '   knowledge base — what it covers, how it is laid out, what it should be able to answer —',
    '   and the most important context for any task here.',
  ];

  if (hasRules) {
    lines.push(
      `2. Then read each rule file below with your file tools (\`${RULES_DIR}/\` is a dot-directory,`,
      '   outside the vault index) and follow them as standing instructions for the whole session:',
      '',
      ...rulePaths.map((path) => `- \`${RULES_DIR}/${path}\``),
    );
  }

  return lines.join('\n');
}

/** Every `.md` under `dir`, recursively, as sorted paths relative to `dir`. */
export async function collectRulePaths(fs: VaultFs, dir: string = RULES_DIR): Promise<string[]> {
  const root = normalizeVaultPath(dir);
  if (!(await fs.exists(root))) return [];

  const found: string[] = [];
  async function walk(current: string): Promise<void> {
    const listing = await fs.list(normalizeVaultPath(current));
    for (const filePath of listing.files) {
      const normalized = normalizeVaultPath(filePath);
      if (!normalized.endsWith('.md')) continue;
      if (!normalized.startsWith(`${root}/`)) continue;
      found.push(normalized.slice(root.length + 1));
    }
    for (const folderPath of listing.folders) {
      await walk(folderPath);
    }
  }
  await walk(root);

  return [...new Set(found)].sort((a, b) => a.localeCompare(b));
}

/** Null when the vault is not initialized (no KNOWLEDGE.md). */
export async function readAgentsMdSource(fs: VaultFs): Promise<AgentsMdSource | null> {
  if (!(await fs.exists('KNOWLEDGE.md'))) return null;
  return { rulePaths: await collectRulePaths(fs) };
}

/**
 * Write-on-change: an unconditional write would churn the file's mtime on every
 * plugin load. Skips silently when KNOWLEDGE.md is absent (vault not initialized).
 */
export async function syncAgentsMd(fs: VaultFs): Promise<void> {
  const source = await readAgentsMdSource(fs);
  if (!source) return;

  const fileExists = await fs.exists(AGENTS_MD_PATH);
  const existing = fileExists ? await fs.read(AGENTS_MD_PATH) : null;
  const merged = mergeManagedBlock(existing, renderAgentsMdBlock(source));
  if (!fileExists || merged !== existing) {
    await fs.write(AGENTS_MD_PATH, merged);
  }
}

/**
 * The explicit, user-initiated cleanup: rewrites AGENTS.md as the managed block
 * alone, discarding everything outside the markers (typically the pre-Knowlery
 * instructions a vault carried). Sync never does this on its own.
 */
export async function resetAgentsMd(fs: VaultFs): Promise<void> {
  const source = await readAgentsMdSource(fs);
  if (!source) return;
  await fs.write(AGENTS_MD_PATH, mergeManagedBlock(null, renderAgentsMdBlock(source)));
}
