import type { VaultFs } from './vault-fs';
import { generateOperatingRules } from '../assets/templates';
import { RULES_DIR, readAgentsMdSource } from './agents-md';
import type { AgentsMdSource } from './agents-md';
import { MANAGED_BLOCK_END, MANAGED_BLOCK_START, mergeManagedBlock, wrapManagedBlock } from './managed-block';

export const CLAUDE_MD_PATH = '.claude/CLAUDE.md';
export const CLAUDE_KNOWLEDGE_IMPORT = '@../KNOWLEDGE.md';

/** Markers of the pre-1.5 managed `@rules/*.md` block; stripped on migration. */
const LEGACY_RULE_IMPORTS_START = '<!-- Knowlery rule imports:start -->';
const LEGACY_RULE_IMPORTS_END = '<!-- Knowlery rule imports:end -->';
/** Imports earlier releases wrote outside a managed block; all superseded by the block. */
const LEGACY_IMPORTS = new Set([CLAUDE_KNOWLEDGE_IMPORT, '@../AGENTS.md', '@../SCHEMA.md', '@../INDEX.base']);

/**
 * Claude Code reads CLAUDE.md, not AGENTS.md, and it is the one harness whose
 * `@` imports are hard injection. So its block is the same fixed context the
 * AGENTS.md block asks Codex/OpenCode to go and read, but pulled in for real:
 * `@../KNOWLEDGE.md` first (the user's description of the knowledge base — the
 * most important part of the prompt), then Knowlery's operating rules inlined,
 * then one `@` import per rule file (Claude has no glob import, so the list is
 * regenerated whenever a rule is added or removed). AGENTS.md is deliberately
 * not imported: it exists for harnesses without imports and would only repeat
 * the operating rules.
 */
export function renderClaudeMdBlock(source: AgentsMdSource): string {
  return wrapManagedBlock(
    `Generated by Knowlery for Claude Code: imports KNOWLEDGE.md (your description of this knowledge base), inlines Knowlery's operating rules for this version, and imports each rule in ${RULES_DIR}/. Edit KNOWLEDGE.md or the rule files, not this block; it is rewritten on sync. Claude-specific notes outside the markers are yours and are kept.`,
    [
      CLAUDE_KNOWLEDGE_IMPORT,
      generateOperatingRules().trim(),
      source.rulePaths.map((path) => `@../${RULES_DIR}/${path}`).join('\n'),
    ],
  );
}

/**
 * Converges an existing file instead of overwriting it. A file that already has
 * the managed block gets it replaced in place. A pre-block file has its Knowlery
 * imports removed first — the 1.5 `@../AGENTS.md`, the pre-1.5 `@../KNOWLEDGE.md`
 * and managed `@rules/*.md` block, stale `@../SCHEMA.md` / `@../INDEX.base` —
 * then the block goes first and whatever the user wrote follows.
 */
export function mergeClaudeMd(existing: string | null, block: string): string {
  if (existing === null) return mergeManagedBlock(null, block);
  if (existing.includes(MANAGED_BLOCK_START) && existing.includes(MANAGED_BLOCK_END)) {
    return mergeManagedBlock(existing, block);
  }
  return mergeManagedBlock(stripLegacyImports(existing), block);
}

function stripLegacyImports(text: string): string {
  const withoutLegacyBlock = text.replace(
    new RegExp(`${escapeRegExp(LEGACY_RULE_IMPORTS_START)}[\\s\\S]*?${escapeRegExp(LEGACY_RULE_IMPORTS_END)}\\n?`, 'g'),
    '',
  );
  const lines = withoutLegacyBlock.split(/\r?\n/).filter((line) => {
    const trimmed = line.trim();
    return !/^@rules\/.+\.md$/.test(trimmed) && !LEGACY_IMPORTS.has(trimmed);
  });
  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trim();
}

/**
 * Write-on-change, so a reload never churns the file's mtime. Skips silently when
 * KNOWLEDGE.md is absent (vault not initialized) — the block would import a file
 * that does not exist.
 */
export async function syncClaudeMd(fs: VaultFs): Promise<void> {
  const source = await readAgentsMdSource(fs);
  if (!source) return;

  const fileExists = await fs.exists(CLAUDE_MD_PATH);
  const existing = fileExists ? await fs.read(CLAUDE_MD_PATH) : null;
  const merged = mergeClaudeMd(existing, renderClaudeMdBlock(source));
  if (!fileExists) await fs.mkdir('.claude');
  if (!fileExists || merged !== existing) {
    await fs.write(CLAUDE_MD_PATH, merged);
  }
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
